### ISSUE TITLE
track multiple rigid bodies

### ISSUE THREAD

**Issue by Akash-Pardasani** [ros-drivers/mocap_optitrack#23] opened 2016-12-10 13:37 UTC
@tonybaltovski Could you please guide on how to track multiple rigid bodies using mocap_optitrack.
It works fine with a single body but when tracking two, i get the following output on terminal 
![mocap](https://cloud.githubusercontent.com/assets/19797245/21073673/5ecca32e-bf0b-11e6-9683-c423fdad8980.png)
I am using motive 1.10.1 and I also found this online(it doesn't work as well)[multiple_rigid_bodies](http://answers.ros.org/question/217341/multiple-rigid-bodies-crash-optitrack-node/)
Any help would be appreciated

**Comment by tonybaltovski** [comment] 2017-01-08 20:52
I use this fine with Motive 1.7.0.  Can you provide your configuration for this node and Motive?  Also, try launch with the screen option to get more information.

**Comment by lericson** [comment] 2017-02-15 22:04
I had the same issue. Fixed in #24 .

**Comment by neudinglei** [comment] 2017-05-03 12:25
@Akash-Pardasani @tonybaltovski @lericson @wjwwood @trainman419 
Now,I want to do collaborative research with my colleagues by the Crazyflie2.0. I am using the optitrack system and ros package mocap_optitrack.The problem is that it can not communicate with three or more Crazyflie2.0。Can you give me some advice and solutions?Thank you very much!

**Comment by tonybaltovski** [comment] 2021-02-25 14:29
Closing due to inactivity.  Please feel free to re-open if issue persists.

**Closed by tonybaltovski** 2021-02-25 14:29 UTC
